name: teaching_children
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # 🔥 أيقونة التطبيق
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  # 📁 assets
  assets:
    - assets/images/
    - assets/images/Arabic_letters/
    - assets/sounds/
    - assets/

  # 🎨 الخطوط
  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
        - asset: assets/fonts/ElMessiri-Medium.ttf
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700


# 🔥 إعداد أيقونة التطبيق
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"